investigaciones css re design / Temas styles deleted, sections order …
edipoarg/caba pull request #39
Opened 2024-07-10 15:54 UTC by alexaiconejo

…modified, colors modified, img size modified, arrow icon added

2024-07-10 15:59 UTC, juanigaray commented
PR chiquito, gracias por escuchar y responder ❤️

2024-07-10 16:13 UTC, alexaiconejo commented
se había desconfigurado mi eslint y no estaba formateando los documentos. Ahi corre bien el lint

2024-07-10 16:28 UTC, juanigaray requested changes
Los tres commits hacen lo mismo.

 `git rebase -i HEAD~3`
 
 A los dos commits de formatting, les ponés un `f` de fixup en vez de pick, así se fusionan con el primer commit.
 
 Después de eso, pusheás con `--force-with-lease` 

La explicación más detallada de esto está acá

https://www.notion.so/C-mo-cuidar-tu-historial-en-Git-cca0044ea1504c76baa9beeb7e60b124

2024-07-15 18:41 UTC, juanigaray approved these changes

2024-07-15 18:42 UTC, merged